# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ThermoStateCalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__frm_StateCalculator(object):
    def setupUi(self, _frm_StateCalculator):
        _frm_StateCalculator.setObjectName("_frm_StateCalculator")
        _frm_StateCalculator.resize(800, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(_frm_StateCalculator)
        self.verticalLayout.setObjectName("verticalLayout")

        # Units Group Box (unchanged)
        self._grp_Units = QtWidgets.QGroupBox(_frm_StateCalculator)
        self._grp_Units.setObjectName("_grp_Units")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self._grp_Units)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._rdo_SI = QtWidgets.QRadioButton(self._grp_Units)
        self._rdo_SI.setChecked(True)
        self._rdo_SI.setObjectName("_rdo_SI")
        self.horizontalLayout_2.addWidget(self._rdo_SI)
        self._rdo_English = QtWidgets.QRadioButton(self._grp_Units)
        self._rdo_English.setObjectName("_rdo_English")
        self.horizontalLayout_2.addWidget(self._rdo_English)
        self.verticalLayout.addWidget(self._grp_Units)

        # Specified Properties Group Box (modified for two states)
        self._grp_SpecifiedProperties = QtWidgets.QGroupBox(_frm_StateCalculator)
        self._grp_SpecifiedProperties.setObjectName("_grp_SpecifiedProperties")
        self.gridLayout = QtWidgets.QGridLayout(self._grp_SpecifiedProperties)
        self.gridLayout.setObjectName("gridLayout")

        # State 1 Group Box
        self._grp_State1 = QtWidgets.QGroupBox(self._grp_SpecifiedProperties)
        self._grp_State1.setObjectName("_grp_State1")
        self.gridLayout_State1 = QtWidgets.QGridLayout(self._grp_State1)
        self.gridLayout_State1.setObjectName("gridLayout_State1")

        # State 1 Property 1
        self._lbl_State1_Property1 = QtWidgets.QLabel(self._grp_State1)
        self._lbl_State1_Property1.setObjectName("_lbl_State1_Property1")
        self.gridLayout_State1.addWidget(self._lbl_State1_Property1, 0, 0, 1, 1)

        self._cmb_State1_Property1 = QtWidgets.QComboBox(self._grp_State1)
        self._cmb_State1_Property1.setObjectName("_cmb_State1_Property1")
        self.gridLayout_State1.addWidget(self._cmb_State1_Property1, 1, 0, 1, 2)

        self._le_State1_Property1 = QtWidgets.QLineEdit(self._grp_State1)
        self._le_State1_Property1.setObjectName("_le_State1_Property1")
        self.gridLayout_State1.addWidget(self._le_State1_Property1, 2, 0, 1, 1)

        self._lbl_State1_Property1_Units = QtWidgets.QLabel(self._grp_State1)
        self._lbl_State1_Property1_Units.setObjectName("_lbl_State1_Property1_Units")
        self.gridLayout_State1.addWidget(self._lbl_State1_Property1_Units, 2, 1, 1, 1)

        # State 1 Property 2
        self._lbl_State1_Property2 = QtWidgets.QLabel(self._grp_State1)
        self._lbl_State1_Property2.setObjectName("_lbl_State1_Property2")
        self.gridLayout_State1.addWidget(self._lbl_State1_Property2, 0, 3, 1, 1)

        self._cmb_State1_Property2 = QtWidgets.QComboBox(self._grp_State1)
        self._cmb_State1_Property2.setObjectName("_cmb_State1_Property2")
        self.gridLayout_State1.addWidget(self._cmb_State1_Property2, 1, 3, 1, 2)

        self._le_State1_Property2 = QtWidgets.QLineEdit(self._grp_State1)
        self._le_State1_Property2.setObjectName("_le_State1_Property2")
        self.gridLayout_State1.addWidget(self._le_State1_Property2, 2, 3, 1, 1)

        self._lbl_State1_Property2_Units = QtWidgets.QLabel(self._grp_State1)
        self._lbl_State1_Property2_Units.setObjectName("_lbl_State1_Property2_Units")
        self.gridLayout_State1.addWidget(self._lbl_State1_Property2_Units, 2, 4, 1, 1)

        self.gridLayout.addWidget(self._grp_State1, 0, 0, 1, 1)

        # State 2 Group Box
        self._grp_State2 = QtWidgets.QGroupBox(self._grp_SpecifiedProperties)
        self._grp_State2.setObjectName("_grp_State2")
        self.gridLayout_State2 = QtWidgets.QGridLayout(self._grp_State2)
        self.gridLayout_State2.setObjectName("gridLayout_State2")

        # State 2 Property 1
        self._lbl_State2_Property1 = QtWidgets.QLabel(self._grp_State2)
        self._lbl_State2_Property1.setObjectName("_lbl_State2_Property1")
        self.gridLayout_State2.addWidget(self._lbl_State2_Property1, 0, 0, 1, 1)

        self._cmb_State2_Property1 = QtWidgets.QComboBox(self._grp_State2)
        self._cmb_State2_Property1.setObjectName("_cmb_State2_Property1")
        self.gridLayout_State2.addWidget(self._cmb_State2_Property1, 1, 0, 1, 2)

        self._le_State2_Property1 = QtWidgets.QLineEdit(self._grp_State2)
        self._le_State2_Property1.setObjectName("_le_State2_Property1")
        self.gridLayout_State2.addWidget(self._le_State2_Property1, 2, 0, 1, 1)

        self._lbl_State2_Property1_Units = QtWidgets.QLabel(self._grp_State2)
        self._lbl_State2_Property1_Units.setObjectName("_lbl_State2_Property1_Units")
        self.gridLayout_State2.addWidget(self._lbl_State2_Property1_Units, 2, 1, 1, 1)

        # State 2 Property 2
        self._lbl_State2_Property2 = QtWidgets.QLabel(self._grp_State2)
        self._lbl_State2_Property2.setObjectName("_lbl_State2_Property2")
        self.gridLayout_State2.addWidget(self._lbl_State2_Property2, 0, 3, 1, 1)

        self._cmb_State2_Property2 = QtWidgets.QComboBox(self._grp_State2)
        self._cmb_State2_Property2.setObjectName("_cmb_State2_Property2")
        self.gridLayout_State2.addWidget(self._cmb_State2_Property2, 1, 3, 1, 2)

        self._le_State2_Property2 = QtWidgets.QLineEdit(self._grp_State2)
        self._le_State2_Property2.setObjectName("_le_State2_Property2")
        self.gridLayout_State2.addWidget(self._le_State2_Property2, 2, 3, 1, 1)

        self._lbl_State2_Property2_Units = QtWidgets.QLabel(self._grp_State2)
        self._lbl_State2_Property2_Units.setObjectName("_lbl_State2_Property2_Units")
        self.gridLayout_State2.addWidget(self._lbl_State2_Property2_Units, 2, 4, 1, 1)

        self.gridLayout.addWidget(self._grp_State2, 1, 0, 1, 1)

        # Warning label and Calculate button
        self._lbl_Warning = QtWidgets.QLabel(self._grp_SpecifiedProperties)
        self._lbl_Warning.setText("")
        self._lbl_Warning.setObjectName("_lbl_Warning")
        self.gridLayout.addWidget(self._lbl_Warning, 2, 0, 1, 1)

        self._pb_Calculate = QtWidgets.QPushButton(self._grp_SpecifiedProperties)
        self._pb_Calculate.setObjectName("_pb_Calculate")
        self.gridLayout.addWidget(self._pb_Calculate, 3, 0, 1, 1)

        self.verticalLayout.addWidget(self._grp_SpecifiedProperties)

        # State Properties Group Box (modified for three columns)
        self._grp_StateProperties = QtWidgets.QGroupBox(_frm_StateCalculator)
        self._grp_StateProperties.setObjectName("_grp_StateProperties")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._grp_StateProperties)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # State 1 Properties
        self._grp_State1_Properties = QtWidgets.QGroupBox(self._grp_StateProperties)
        self._grp_State1_Properties.setObjectName("_grp_State1_Properties")
        self.verticalLayout_State1 = QtWidgets.QVBoxLayout(self._grp_State1_Properties)
        self.verticalLayout_State1.setObjectName("verticalLayout_State1")

        self._lbl_State1 = QtWidgets.QLabel(self._grp_State1_Properties)
        self._lbl_State1.setObjectName("_lbl_State1")
        self.verticalLayout_State1.addWidget(self._lbl_State1)

        self._lbl_State1_Properties = QtWidgets.QLabel(self._grp_State1_Properties)
        self._lbl_State1_Properties.setObjectName("_lbl_State1_Properties")
        self.verticalLayout_State1.addWidget(self._lbl_State1_Properties)

        self.horizontalLayout.addWidget(self._grp_State1_Properties)

        # State 2 Properties
        self._grp_State2_Properties = QtWidgets.QGroupBox(self._grp_StateProperties)
        self._grp_State2_Properties.setObjectName("_grp_State2_Properties")
        self.verticalLayout_State2 = QtWidgets.QVBoxLayout(self._grp_State2_Properties)
        self.verticalLayout_State2.setObjectName("verticalLayout_State2")

        self._lbl_State2 = QtWidgets.QLabel(self._grp_State2_Properties)
        self._lbl_State2.setObjectName("_lbl_State2")
        self.verticalLayout_State2.addWidget(self._lbl_State2)

        self._lbl_State2_Properties = QtWidgets.QLabel(self._grp_State2_Properties)
        self._lbl_State2_Properties.setObjectName("_lbl_State2_Properties")
        self.verticalLayout_State2.addWidget(self._lbl_State2_Properties)

        self.horizontalLayout.addWidget(self._grp_State2_Properties)

        # State Change Properties
        self._grp_StateChange_Properties = QtWidgets.QGroupBox(self._grp_StateProperties)
        self._grp_StateChange_Properties.setObjectName("_grp_StateChange_Properties")
        self.verticalLayout_StateChange = QtWidgets.QVBoxLayout(self._grp_StateChange_Properties)
        self.verticalLayout_StateChange.setObjectName("verticalLayout_StateChange")

        self._lbl_StateChange = QtWidgets.QLabel(self._grp_StateChange_Properties)
        self._lbl_StateChange.setObjectName("_lbl_StateChange")
        self.verticalLayout_StateChange.addWidget(self._lbl_StateChange)

        self._lbl_StateChange_Properties = QtWidgets.QLabel(self._grp_StateChange_Properties)
        self._lbl_StateChange_Properties.setObjectName("_lbl_StateChange_Properties")
        self.verticalLayout_StateChange.addWidget(self._lbl_StateChange_Properties)

        self.horizontalLayout.addWidget(self._grp_StateChange_Properties)

        self.verticalLayout.addWidget(self._grp_StateProperties)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(_frm_StateCalculator)
        QtCore.QMetaObject.connectSlotsByName(_frm_StateCalculator)

    def retranslateUi(self, _frm_StateCalculator):
        _translate = QtCore.QCoreApplication.translate
        _frm_StateCalculator.setWindowTitle(_translate("_frm_StateCalculator", "Two-State Thermodynamic Calculator"))
        self._grp_Units.setTitle(_translate("_frm_StateCalculator", "System of Units"))
        self._rdo_SI.setText(_translate("_frm_StateCalculator", "SI"))
        self._rdo_English.setText(_translate("_frm_StateCalculator", "English"))
        self._grp_SpecifiedProperties.setTitle(_translate("_frm_StateCalculator", "Specified Properties"))

        # State 1
        self._grp_State1.setTitle(_translate("_frm_StateCalculator", "State 1"))
        self._lbl_State1_Property1.setText(_translate("_frm_StateCalculator", "Property 1"))
        self._lbl_State1_Property2.setText(_translate("_frm_StateCalculator", "Property 2"))
        self._le_State1_Property1.setText(_translate("_frm_StateCalculator", "1.0"))
        self._le_State1_Property2.setText(_translate("_frm_StateCalculator", "100.0"))
        self._lbl_State1_Property1_Units.setText(_translate("_frm_StateCalculator", "Bar"))
        self._lbl_State1_Property2_Units.setText(_translate("_frm_StateCalculator", "C"))

        # State 2
        self._grp_State2.setTitle(_translate("_frm_StateCalculator", "State 2"))
        self._lbl_State2_Property1.setText(_translate("_frm_StateCalculator", "Property 1"))
        self._lbl_State2_Property2.setText(_translate("_frm_StateCalculator", "Property 2"))
        self._le_State2_Property1.setText(_translate("_frm_StateCalculator", "1.0"))
        self._le_State2_Property2.setText(_translate("_frm_StateCalculator", "100.0"))
        self._lbl_State2_Property1_Units.setText(_translate("_frm_StateCalculator", "Bar"))
        self._lbl_State2_Property2_Units.setText(_translate("_frm_StateCalculator", "C"))

        # Populate combo boxes
        properties = [
            "Pressure (p)", "Temperature (T)", "Quality (x)",
            "Specific Internal Energy (u)", "Specific Enthalpy (h)",
            "Specific Volume (v)", "Specific Entropy (s)"
        ]

        for prop in properties:
            self._cmb_State1_Property1.addItem(_translate("_frm_StateCalculator", prop))
            self._cmb_State1_Property2.addItem(_translate("_frm_StateCalculator", prop))
            self._cmb_State2_Property1.addItem(_translate("_frm_StateCalculator", prop))
            self._cmb_State2_Property2.addItem(_translate("_frm_StateCalculator", prop))

        # Set default selections
        self._cmb_State1_Property1.setCurrentIndex(0)  # Pressure
        self._cmb_State1_Property2.setCurrentIndex(1)  # Temperature
        self._cmb_State2_Property1.setCurrentIndex(0)  # Pressure
        self._cmb_State2_Property2.setCurrentIndex(1)  # Temperature

        self._pb_Calculate.setText(_translate("_frm_StateCalculator", "Calculate"))
        self._grp_StateProperties.setTitle(_translate("_frm_StateCalculator", "State Properties"))

        # State displays
        self._grp_State1_Properties.setTitle(_translate("_frm_StateCalculator", "State 1 Properties"))
        self._lbl_State1.setText(_translate("_frm_StateCalculator", "State 1:"))
        self._lbl_State1_Properties.setText(_translate("_frm_StateCalculator", "Properties will be calculated here"))

        self._grp_State2_Properties.setTitle(_translate("_frm_StateCalculator", "State 2 Properties"))
        self._lbl_State2.setText(_translate("_frm_StateCalculator", "State 2:"))
        self._lbl_State2_Properties.setText(_translate("_frm_StateCalculator", "Properties will be calculated here"))

        self._grp_StateChange_Properties.setTitle(_translate("_frm_StateCalculator", "State Change"))
        self._lbl_StateChange.setText(_translate("_frm_StateCalculator", "Change from State 1 to State 2:"))
        self._lbl_StateChange_Properties.setText(_translate("_frm_StateCalculator", "Changes will be calculated here"))